### ISSUE TITLE
nonce too low

### ISSUE THREAD

**Issue by j10sanders** [INFURA/infura#109]
Hello,

I am trying to publish my contract on the mainnet, using Truffle.  I'm able to use Infura to publish to Ropsten, but when I try to publish to the mainnet, I get this error:

`Error encountered, bailing. Network state unknown. Review successful transactions manually.
nonce too low`

Any suggestions?

**Comment by j10sanders** [comment]
Thanks @jamatulli .  Yes, I was able to migrate later.

This seems to be a pretty serious bug, imo, since **I did have to pay the gas fee.**  

Thanks for your help.

**Comment by jamatulli** [comment]
@j10sanders I see that you mentioned it on Gitter that you were successful.  The issue seems to be getting attention from the Truffle crew.  

After a little more research I see related problems referenced in that are being addressed as well.  Hopefully these will be solved in an near future release, perhaps with the incorporation of Web3 v1.0.0 event emitters into contract deployment.  I will try to make a note here if I see anything pertinent.
