### ISSUE TITLE
RuntimeError: Function transfer is not constant: transfer, requires to sign transaction

### ISSUE THREAD

**Issue by marknguyen85** [INFURA/infura#120]
i'm try transfer my erc token and code below

```
web3 = Web3::Eth::Rpc.new host: 'ropsten.infura.io', 
                                port: 443,  
                                connect_options: {
                                    open_timeout: 20,
                                    read_timeout: 140,
                                    use_ssl: true,
                                    rpc_path: '/xxxxxxxxxx'
                                }
ERC_ABI = '[{.....}]'
contractAddr = "0xFf............"
contract = web3.eth.contract(ERC_ABI).at(contractAddr)
contract.transfer.getData('0xg.......', 10000)
```

then get error 

`RuntimeError: Function transfer is not constant: transfer, requires to sign transaction`

pls help me

thanks much.

**Comment by jamatulli** [comment]
@marknguyen85 Assuming you are following the ERC20 Token Standard than you would use: 

`contract.transfer(address to, uint tokens)`

Documentation for this is [here](https://theethereum.wiki/w/index.php/ERC20_Token_Standard).

However, you can not simply transfer without a signed transaction because you are changing the contract state.  The first part of the error (which is being produced by the Ruby web3 library you are using) is telling you that the function "transfer" is not marked with the modifier "constant". (Note: the "constant" modifier is deprecated in favor of "view" or "pure" per documentation [here](http://solidity.readthedocs.io/en/develop/contracts.html#view-functions)). A function that is not marked as "view" or "pure" is assumed to change the state of the contract and so requires a signed transaction.  (http://solidity.readthedocs.io/en/develop/contracts.html#view-functions).

So if you want to transfer tokens then you will need to sign a transaction containing your contract.transfer() in the data.  

Looking at the Ruby web3 library izetex/web3-eth that you appear to be using there doesn't seem to be a way to create a signed transaction.  You may want to look into using [EthWorks/ethereum.rb](https://github.com/izetex/web3-eth/blob/34a5dd6a4091fa7865457eec5da13fae35ba626c/lib/web3/eth/contract.rb) as it can use the 'eth' gem available from se3000/ruby-eth to sign transactions.  From your previous questions I believe you are already familiar with how this works and the documentation from ethereum.rb seems to simplify it.

Hope this helps.

**Comment by jamatulli** [comment]
@marknguyen85 were you able submit a signed transaction or otherwise resolve this particular issue?
