### ISSUE TITLE
Ropsten Infura is behind

### ISSUE THREAD

**Issue by owocki** [INFURA/infura#151]
Ropsten Infura is behind .

to reproduce, set your truffle to ropsten RPC: `https://ropsten.infura.io/`

```
truffle(ropsten)> web3.eth.getBlock('latest', function(one,two){console.log(one,two['number']);});
undefined
truffle(ropsten)> null 4230742
```

should be closer to 4238008

**Comment by ryanschneider** [comment]
It’s apparently an issue with geth, we are hoping for a hotfix early next week but will switch over to using parity for ropsten instead if it’s not resolved soon.

**Comment by ryanschneider** [comment]
Correction, it's actually an issue w/ parity, see the allcoredevs gitter for details.  But the issue is that parity and geth currently don't agree on the implementation of `sstore` so there are multiple ropsten chains at the moment and most miners are running parity, which is why geth appears to be stalled.

Hopefully we'll get more clarity today, but it sounds like parity will need to hotfix and convince miners to switch to geth's chain, which should then surpass the old parity chain in total difficulty and everything should be good to go.

**Comment by ryanschneider** [comment]
This is resolved, the issue was the eth clients couldn't keep up with all the competing chains after the issues with the fork.
