### ISSUE TITLE
JSON RPC returns "0x" as response sometimes

### ISSUE THREAD

**Issue by exarus** [INFURA/infura#157]
I've faced an issue of getting invalid response for my request to mainnet Infura through HTTPS.

## Request description

I'm sending a valid batch request that queries for uint256.
I'm taking "latest" block number and explicitly specify it in request.
I expect to recieve uint256 balance from RPC.
But sometimes Infura returns "0x" as result.
```json
[{"jsonrpc":"2.0","id":751,"result":"0x"}]
```

According to JSON RPC spec ( https://github.com/ethereum/wiki/wiki/JSON-RPC#hex-value-encoding ) it's not a valid value for uint256.
I doubt if it's an actual zero or an error notifcation.
Retry SOLVES the issue. The response gets valid after retry or 2.

Example request:
```json
[{"jsonrpc":"2.0","id":751,"method":"eth_call","params":[{"data":"0xf7888aec0000000000000000000000008f207f9b97cf0afc292a384d6c19a2a084acde5e0000000000000000000000000ef1b82b6801944b9ac3d29ab210eee923c73efe","to":"0xa5cc679a3528956e8032df4f03756c077c1ee3f4"},"0x65b559"]}]
```

Sometimes we get a good response:
```json
[{"jsonrpc":"2.0","id":751,"result":"0x0000000000000000000000000000000000000000000000000000000000000000"}]
```

Sometimes we get a bad response:
```json
[{"jsonrpc":"2.0","id":751,"result":"0x"}]
```

Please, ask me if I'm in doubt. I feel that issue is important, so I'm glad to provide any support possible.

**Comment by exarus** [comment]
I've tested sending N similar requests simultaneously. Some of them fail, some doesn't.
The tests took `"latest"` block number from Infura. And for each `eth_call` used that block number as parameter.

I've performed same tests for `"latest"` block. It worked fine.

I think that I might found a reason.
So I get latest block number. Let it be `"0x65b559"`.
After that I'm `call`-ing some RPC requests passing that block number as param,.
My requests are facing balance loader.
After that some requests are handled by nodes that are aware about `"0x65b559"` block and FEW requests go to nodes that is not yet aware about block `"0x65b559"`. So they can't handle the request and return:
```json
[{"jsonrpc":"2.0","id":751,"result":"0x"}]
```

Hope, my tests helped to figure out what's wrong.

**Comment by zmadmani** [comment]
I'm also getting this consistently for read transactions to the blockchain. Something as simple as just reading the balanceOf function of a ERC-20 token fails about 1/10 times through the infura mainnet endpoint in metamask but works every time when running a local geth instance. 

I'm using the new web3 1.x API and interacting with the contract as follows: 

`
    var resp = await contract.methods.balanceOf(address).call()
`

The error that is returned through web3 is "Couldn't decode uint256 from ABI: 0x" which makes sense since the raw output is 0x. It only errors out about once in 10 times but once it has, it seems like the response of 0x is cached and consistently errors out until i clear the page and reload. On reload, a different call to balanceOf will respond this way and so on.

I am not indicating any blockNumber as exarus did rather a simple read call. Also note that once i run my own local node, everything works perfectly.

Any idea on what may be going on?

**Comment by AyushBherwani1998** [comment]
@zmadmani did you manage to solve the issue?

**Comment by exarus** [comment]
I am closing the issue, because of zero activity. Infura probably changed a lot after 4 years and I haven't tested if the problem persists.
