### ISSUE TITLE
Whitelist Origins Not Working on Safari

### ISSUE THREAD

**Issue by devstein** [INFURA/infura#180]
I whitelisted my domain and verified it worked on Chrome, Brave, Firefox, and iOS Safari, but when I tested Safari I received a `403` forbidden. Once I removed my domain from the whitelist, Safari worked again. This is not a CORs issue. 

I'm using the latest [web3 v1.0.0-beta.52](https://github.com/ethereum/web3.js/releases/tag/v1.0.0-beta.52)

Any help is appreciated!

**Comment by egalano** [comment]
Thanks for reporting! Our team is looking into this.

**Comment by ryanschneider** [comment]
Thanks @devstein I believe we've identified the issue and will be deploying a fix for it around 2019-04-09 17:00 UTC (so in about 24 hours from the time of this post).

**Comment by ryanschneider** [comment]
@devstein the fix for your issue has been deployed, please let us know if you continue to have issues.

Also, we'll be updating our docs to reflect this, but for the Origin whitelist you can enter either a hostname by itself or with a scheme (e.g. `https://mysite.tld` or `mysite.tld`).  If you enter a scheme then the whitelist will only match that scheme (to force https, for example), if you enter just a hostname any scheme will work.  Schemes work with wildcard subdomains as well (e.g. `https://*.mysite.tld`).

**Comment by devstein** [comment]
@ryanschneider @egalano Thanks! I'll let you know if anything comes up
