### ISSUE TITLE
getBlock(Latest) and eth_call block.number can differs

### ISSUE THREAD

**Issue by wighawag** [INFURA/infura#31]
Hi,

It is probably due to allow scaling (by having different server for different calls) but this behavior is unfortunate. It has cost us some ether until as we were not watching while this was happening :

Our backend script get the timestamp of the last block returned by getBlock("Latest") to ensure we are not reading stale data from the chain.

From that point we use eth_call to gather data assuming the data is from that latest block at least. We then execute our transaction that has some relatively high gas cost.

Unfortunately sometime (like now probably due to high usage of ethereum) eth_call block.number is far outdated (5 days ago) compared to the block number returned by getBlock("Latest"). 

Our assumption break down and our script keep trying to execute that transaction that get mined but get an exception.

We fixed our issue by reading the blockNumber from the same eth_call that gather data  instead. So we are sure the data is up to date compared to the latest block. 

It would be cool if there would be a way to attach ourselves to a particular node so that the call to that node are consistent.

Thanks

**Comment by wighawag** [comment]
Actually I just realized I can pass a block number to eth_call so I should be able to solve my issue by ensuring I get some value.

**Comment by wighawag** [comment]
Hmm, I am using the blockNumber I get from getBlock("Latest") to use it instead of the defaultBlock in eth_calls but this seems to always make these call return 0 for block.number.

What is the behavior supposed to be for a node that receive a eth_call for a block that it still did not get? is it to return 0 for block.number ?

**Comment by egalano** [comment]
Hi @wighawag this was due to an issue several months ago where our health checks failed to detect nodes that were falling out of sync when they were under heavy load. In addition to improving our automated scaling, we have since implemented more stringent monitoring to minimize the chance of these types of errors occurring in the future. Our team is going through rapid growth as our traffic has scaled over 30x what it was at this time last year. Thanks for being patient and understanding as our team grows and we continue to improve our infrastructure. Please open a new issue if you see this error again.
