### ISSUE TITLE
web3.getBlock(blockNumber, true) returns null for some blocks

### ISSUE THREAD

**Issue by farhankhwaja** [INFURA/infura#43]
This issue has started happening lately. Certain blocks don't get back any information. I have the logs of blocks failed:
```

Web3.getBlock Failed.
Block Failed: 4689234.

ERROR: Cannot read property 'transactions' of null
----------------------------
Error Description:
Web3.getBlock Failed.
Block Failed: 4689205.

ERROR: Cannot read property 'transactions' of null
```
This is happening on the MainNet.

Like the above two there are many examples. web3.getBlock() call returns null. Is the client lagging behind or still updating ancient blocks (as per [this Github Parity issue](https://github.com/paritytech/parity/issues/6334))

**Comment by egalano** [comment]
This was a result of heavy load on our RPC nodes. The null is returned when the request is serviced by a node which is lagging by several blocks. The issue was resolved for now but occasional issues like this will occur as a result of heavy load from popular dapps. We are working on ways to stabilize the network in times of heavy load. We'll be writing a blog post soon detailing our architecture changes.

**Comment by jdkanani** [comment]
@egalano Getting `null` too often. Any solution?

**Comment by johanherman** [comment]
Hi @jdkanani. As @egalano was explaining earlier this can happen sometimes. So could you please clarify what you mean when you're saying that you're seeing this "too often"? Weekly? Daily? Hourly? Intermittent during the time period you're referring to, or consistently? For the same block nr, or different ones?

**Comment by johanherman** [comment]
Closing this issue for now. Don't hesitate to reach out if you've got further comments about this @jdkanani.

**Comment by wallaceturner** [comment]
Not sure why this bug is closed as it still regularly occurs; if you subscribe to `newBlockHeaders` and then query the blockchain in the callback you will get a null block after a few minutes.
A solution I am using is to simply 'wait' a little bit if the block is null
for example

```
                let block:any = null;
                let count = 0;
		while(( block = await this.web3.eth.getBlock(i, true)) == null && count < 20){
                    count++;
                    logger.info(`getBlock returned null for ${i}. count: ${count}`)
                    await sleep(2000);                    
                }
                if(block){
                    //do something with the block
                }else{
                   throw new Error(`getBlock returned null for ${i}. count${count}`)             
                }
```

for the definition of sleep [see this article][1]:

[1]:https://stackoverflow.com/questions/951021/what-is-the-javascript-version-of-sleep

**Comment by jdkanani** [comment]
@wallaceturner I created `sleepFor` and `retry` decorator for this: https://gist.github.com/jdkanani/2dbf4b461e9f203dfd8a0d78c64f7a1a

Feel free to use this like - 

```js
@retry(10000, 5) // try 5 times with 10sec interval
function getBlock(blockNumber) {
	// Fetch block and return promise 
}
```
