### ISSUE TITLE
infura delay

### ISSUE THREAD

**Issue by xu1guang** [INFURA/infura#44]
Hi, I noticed that by using infura endpoint there is a 700 blocks delay on the main net. Is this normal?

**Comment by egalano** [comment]
It is not @xu1guang we're currently experiencing a service degradation of our blockNumber API. Other parts of the API are still functioning such as eth_call, sending transactions, and event lookups but we're working to bring our blockNumber API back up to date. Sorry for the inconvenience we'll update this ticket once the issue is resolved.

**Comment by egalano** [comment]
Sorry for the delayed update. Our blockNumber API was restored at approximately 19:00 UTC. Please let us know if you are still seeing significant block lag.
